stages:
  - docker
  - announce

build-docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - master

telegram:
  stage: announce
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  script:
    - git changelog --format telegram-html --since yesterday >chlog
    - announce-telegram chlog "$CHAT_IDS"
  only:
    - master
