stages:
  - docker
  - announce

build-docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

telegram:
  stage: announce
  image: registry.gitlab.com/clovis-ai/dotfiles
  script:
    - git changelog --format telegram-markdown --since yesterday >chlog
    - announce-telegram chlog "$CHAT_IDS"

