#!/bin/bash

CONFIG="$HOME/.config/clovis-probe"
REMOTES=$(cat "$CONFIG/remotes")

ERRORS=$(mktemp)

declare -A FOUND

number=$(<<<"$REMOTES" wc -l)
i=0
for remote in $HOSTNAME $REMOTES
do
	announce "($i/$number): $remote"

	COMMAND=""
	[[ $remote != "$HOSTNAME" ]] && COMMAND="ssh -At $remote"

	users=$($COMMAND who 2>$ERRORS | grep -v 'scripts/announce' | cut -d ' ' -f 1 | uniq)
	for user in $users
	do
		if [[ $user == "$USER" ]]
		then
			echo -n ""
		else
			echo "Found user $user here!"
			FOUND[$user]="${FOUND[$user]} $remote"
		fi
	done

	i=$((i+1))
done

announce -n "Results:"
for user in "${!FOUND[@]}"
do
	echo "$user → ${FOUND[$user]}"
done | sort | column -t

errors=$(cat $ERRORS | grep -v "Connection to .* closed.")
if [[ $(<<<"$errors" wc -l) == 0 ]]; then
	announce -n "Errors:"
	echo "$errors"
fi
