#!/usr/bin/env bash

last_user=""
number_occurences=0
while IFS= read -r line; do
	user=$(cut <<<"$line" -d ' ' -f 1)
	#    from=$(<<<"$line" cut -d ' ' -f 4-8)
	#    to=$(<<<"$line" cut -d ' ' -f 10-14)
	#    on=$(<<<"$line" cut -d ' ' -f 2)

	if [[ $last_user != "$user" ]]; then
		[[ $last_user != "" ]] && echo "$last_user $number_occurences"
		last_user=$user
		number_occurences=0
	else
		number_occurences=$((number_occurences + 1))
	fi
done <<<"$(last -F | tr -s ' ' | sort | sed 's/system boot/systemboot/')"
