#!/bin/bash

case $1 in
enabled)
    hash yay 2>/dev/null || (echo "'yay' is not installed."; exit 1)
    ;;
name)
    echo -n "ArchLinux packages (AUR included)"
    ;;
install)
    shift
    announce "yay -S --needed $*"
    yay -S --needed $*
    ;;
upgrade)
    shift
    announce "yay -Syyuu $*"
    yay -Syyuu $*
    announce "yay -Fy"
    yay -Fy
    ;;
clean)
    announce "Unneeded/orphan packages:"
    yay -Qdt
    announce -nn "Do you want to remove them? (y/N)"
    read -r CHOICE
    case $CHOICE in
    y|Y)
        packager remove "$(yay -Qdt)"
        ;;
    esac
    announce "Cleaning of the package cache:"
    echo " u. Remove uninstalled packages from the cache"
    echo " i. Remove everything from the cache (not recommended)"
    echo " n. Do not clean the cache"
    announce -nn "Do you want to clean the cache? (u/i/N)"
    read -r CHOICE
    case $CHOICE in
    u)
        announce "yay -Sc"
        yay -Sc;;
    i)
        announce "yay -Scc"
        yay -Scc;;
    esac
    ;;
remove)
    shift
    announce "yay -R $*"
    yay -R --confirm $*
    ;;
purge)
    shift
    announce "yay -Rncs $*"
    yay -Rncs --confirm $*
    ;;
search)
    shift
    announce "Where do you want to search on?"
    echo " 0. All packages"
    echo " 1. Installed packages"
    echo " 2. Search for a file"
    echo " 3. List files owned by a package"
    announce -nn "Your choice:"
    read -r CHOICE
    case $CHOICE in
    0|a|all)
        announce "yay -Ss $*"
        yay -Ss $*
        ;;
    1|i|installed)
        announce "yay -Qi $*"
        yay -Qi $*
        ;;
    2|f|file)
        announce "yay -F $*"
        yay -F $*
        ;;
    3|files)
    	announce "yay -Ql $*"
    	yay -Ql $*
    	;;
    esac
    ;;
*)
    announce "Invalid command '$1'."
    exit 2
    ;;
esac
