#!/bin/bash

case $1 in
enabled)
    hash apt       2>/dev/null || (echo "'apt' is not installed."; exit 1)
    hash apt-cache 2>/dev/null || (echo "'apt-cache' is not installed."; exit 1)
    ;;
name)
    echo -en "Old Debian package manager. Consider using 'aptitude' instead: https://askubuntu.com/a/1749/871815"
    ;;
install)
    shift
    announce "apt install $*"
    sudo apt install $*
    ;;
upgrade)
    shift
    if [[ $# = 0 ]]
    then
        announce "apt update"
        sudo apt update
        announce "apt --with-new-pkgs --autoremove upgrade"
        sudo apt upgrade
    else
        announce "apt install --only-upgrade $*"
        sudo apt install --only-upgrade $*
    fi
    ;;
purge)
    shift
    announce "apt remove --purge $*"
    sudo apt remove --purge $*
    announce "apt autoremove --purge"
    sudo apt autoremove
    ;;
remove)
    shift
    announce "apt remove $*"
    sudo apt remove $*
    announce "apt autoremove"
    sudo apt autoremove
    ;;
search)
    shift
    announce "apt-cache search $*"
    apt-cache search $*
    ;;
*)
    announce "Invalid command '$1'."
    exit 2
    ;;
esac
