#!/bin/bash

function ensure_sdkman() {
	_sdkman_path="$HOME/.sdkman/bin/sdkman-init.sh"
	[[ -f $_sdkman_path ]] && . "$_sdkman_path"

	if ! declare -f sdk >/dev/null; then
		if [[ ! -f "$_sdkman_path" ]]; then
			curl -s "https://get.sdkman.io" | bash
		fi
		source "$_sdkman_path"
	fi
}

case $1 in
enabled) ;;

name)
	echo -en "Software Development Kit Manager"
	;;
install)
	shift
	ensure_sdkman
	announce run "source $_sdkman_path && sdk install $*"
	;;
upgrade)
	shift
	ensure_sdkman
	announce run "source $_sdkman_path && sdk update"
	announce run "source $_sdkman_path && sdk upgrade $*"
	announce run "source $_sdkman_path && sdk selfupdate"
	;;
purge)
	shift
	announce run "source $_sdkman_path && sdk uninstall $*"
	;;
remove)
	shift
	announce run "source $_sdkman_path && sdk uninstall $*"
	;;
search)
	shift
	announce run "source $_sdkman_path && sdk list $*"
	;;
*)
	announce "Invalid command '$1'."
	exit 2
	;;
esac
