#!/bin/bash

. cl-depend announce "packager-yay"
. cl-depend announce-menu "packager-yay"
. announce-menu --import

case $1 in
enabled)
    hash yay 2>/dev/null || (echo "'yay' is not installed."; exit 1)
    ;;
name)
    echo -n "ArchLinux packages (AUR included)"
    ;;
install)
    shift
    announce "yay -S --needed $*"
    yay -S --needed $*
    ;;
upgrade)
    shift
    announce "yay -Syyuu $*"
    yay -Syyuu $*
    announce "yay -Fy"
    yay -Fy
    ;;
clean)
    announce "Unneeded/orphan packages:"
    yay -Qdt
	announce-menu --title "Do you want to remove them?" --default "no" "yes" "no"
    if announce-menu --chosen "yes"; then
        packager --tool packager-yay remove "$(yay -Qdt | cut -d ' ' -f 1)"
    fi
    announce-menu --title "Cleaning of the package cache:" --default "no" \
    	"uninstalled:Remove uninstalled packages from the cache" \
    	"full:Remove everything from the cache" \
    	"no:Do not clean the cache"
    case $(announce-menu-get) in
    uninstalled)
        announce "yay -Sc"
        yay -Sc;;
    full)
        announce "yay -Scc"
        yay -Scc;;
    esac
    ;;
remove)
    shift
    announce "yay -R $*"
    yay -R --confirm $*
    ;;
purge)
    shift
    announce "yay -Rncs $*"
    yay -Rncs --confirm $*
    ;;
search)
    shift
    announce-menu --title "Where do you want to search on?" \
    	"all:Search for a package with this name" \
    	"installed:Give me information on this package I installed" \
    	"file:Which package owns this file?" \
    	"files:Which files owns this package?"
    case $(announce-menu-get) in
    all)
        announce "yay -Ss $*"
        yay -Ss $*
        ;;
    installed)
        announce "yay -Qi $*"
        yay -Qi $*
        ;;
    file)
        announce "yay -F $*"
        yay -F $*
        ;;
    files)
    	announce "yay -Ql $*"
    	yay -Ql $*
    	;;
    esac
    ;;
*)
    announce "Invalid command '$1'."
    exit 2
    ;;
esac
