#!/bin/bash

. cl-depend announce "packager-yay"
. cl-depend announce-menu "packager-yay"
. announce-menu --import

case $1 in
enabled)
	hash pacman 2>/dev/null || (
		echo "'pacman' is not installed."
		exit 1
	)
	;;
name)
	echo -n "ArchLinux packages (AUR excluded)"
	;;
install)
	shift
	announce sudo "pacman -S --needed $*"
	;;
upgrade)
	shift
	announce sudo "pacman -Syuu $*"
	announce sudo "pacman -Fy"
	;;
clean)
	announce "Unneeded/orphan packages:"
	pacman -Qdt
	announce -nn "Do you want to remove them? (y/N)"
	read -r CHOICE
	case $CHOICE in
	y | Y)
		packager --tool packager-pacman remove "$(pacman -Qdt)"
		;;
	esac
	announce "Cleaning of the package cache:"
	echo " u. Remove uninstalled packages from the cache"
	echo " i. Remove everything from the cache (not recommended)"
	echo " n. Do not clean the cache"
	announce -nn "Do you want to clean the cache? (u/i/N)"
	read -r CHOICE
	case $CHOICE in
	u)
		announce sudo "pacman -Sc"
		;;
	i)
		announce sudo "pacman -Scc"
		;;
	esac
	;;
remove)
	shift
	announce sudo "pacman -R --confirm $*"
	;;
purge)
	shift
	announce sudo "pacman -Rsu --confirm $*"
	;;
search)
	shift
	announce-menu --title "Where do you want to search on?" \
		"all:Search for a package with this name" \
		"installed:Give me information on this package I installed" \
		"file:Where can I find this file?" \
		"files:Show the contents of this package"
	case $(announce-menu-get) in
	all)
		announce run "pacman -Ss $*"
		;;
	installed)
		announce run "pacman -Qi $*"
		;;
	file)
		announce run "pacman -F $*"
		;;
	files)
		announce run "pacman -Ql $*"
		;;
	esac
	;;
*)
	announce "Invalid command '$1'."
	exit 2
	;;
esac
