#!/bin/bash

if [[ $1 == "complete" ]]
then
    complete -o nosort -W "-n --newline-before -r --erase -nn --no-newline-after" announce

    return
fi

if [[ $1 == "-n" || $1 == "--newline-before" ]]
then
    echo
    shift
fi

if [[ $1 == "-r" || $1 == "--erase" ]]
then
    echo -ne "\033[2K\r"
    shift
fi

if [[ $1 == "-nn" || $1 == "--no-newline-after" ]]
then
    PARAMS="-n"
    shift
fi

echo -e $PARAMS "\e[48;5;16m[ \e[94m${USER}@${HOSTNAME}\e[39m ]\e[0m\e[48;5;233m $* \e[0m"
