#!/bin/bash

if [[ $1 == "complete" ]]; then
	complete -o nosort -W "-n --newline-before -r --erase -nn --no-newline-after" announce

	return
fi

if [[ $1 == "-n" || $1 == "--newline-before" ]]; then
	echo
	shift
fi

if [[ $1 == "-r" || $1 == "--erase" ]]; then
	echo -ne "\033[2K\r"
	shift
fi

if [[ $1 == "-nn" || $1 == "--no-newline-after" ]]; then
	PARAMS="-n"
	shift
fi

if [[ $SSH_CLIENT != "" ]]; then
	ssh_name=" ‹\e[32m$USER \e[36m$HOSTNAME\e[0m›"
fi

root_arrow="\e[31m⮕"
if [[ $EUID == 0 ]]; then
	arrow=$root_arrow
else
	arrow="\e[0m→"
fi

if [[ $1 == "run" ]]; then
	shift
	and_exec="$*"
elif [[ $1 == "sudo" ]]; then
	shift
	and_exec="sudo $*"
	arrow=$root_arrow
fi

if [[ $VIRTUAL_ENV != "" ]]; then
	arrow="⚕ $arrow"
fi

echo -e $PARAMS "$ssh_name $arrow \e[34m$* \e[0m"
$and_exec
