#!/bin/bash

#
# announce-telegram
#
# Sends a message to a Telegram chat via the Bot API
#
# Usage:
#	announce-telegram <msg> <chats>
#
# Options:
# 	msg:		a file with the message to send
#	chats:		a file with the IDs of chats the message should be sent to (one ID per line)
#
# Environment variables:
#	BOT_TOKEN:	the token to connect to the Bot API
#

if [[ $# != 2 ]]
then
    announce "Expected 2 arguments, a file with the message, and a file with the list of chats."
    exit 1
fi

if [[ ! -f $1 ]]
then
    announce "File $1 doesn't exist."
    exit 1
fi

if [[ ! -f $2 ]]
then
    announce "File $2 doesn't exist."
    exit 1
fi

if [[ ${BOT_TOKEN:-undefined} == undefined ]]
then
    announce "Missing BOT_TOKEN"
    exit 1
fi

announce "Sending message to the $(<$2 wc -w) chats found."
echo "START OF MESSAGE"
cat $1
echo "END OF MESSAGE"

for CHAT_ID in $(cat $2)
do
    echo "Sending to $CHAT_ID"
    curl -v\
        --data-urlencode "parse_mode=html" \
        --data-urlencode "chat_id=${CHAT_ID}" \
        --data-urlencode "text=$(cat $1)" \
        "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage"
done
