#!/bin/bash

if [[ $1 == "complete" ]]
then
    complete -o nosort -W "-n --newline-before -r --erase -nn --no-newline-after" announce

    return
fi

if [[ $1 == "-n" || $1 == "--newline-before" ]]
then
    echo
    shift
fi

if [[ $1 == "-r" || $1 == "--erase" ]]
then
    echo -ne "\033[2K\r"
    shift
fi

if [[ $1 == "-nn" || $1 == "--no-newline-after" ]]
then
    PARAMS="-n"
    shift
fi

if [[ $SSH_CLIENT != "" ]]; then
	ssh_name=" ‹\e[32m$USER \e[36m$HOSTNAME\e[0m›"
fi

if [[ $EUID == 0 ]]; then
	arrow="\e[31m⮕"
else
	arrow="\e[0m→"
fi

echo -e $PARAMS "$ssh_name $arrow \e[34m$* \e[0m"
