#!/usr/bin/env bash

. announce-menu --import

echo -en "Checking dependencies...\r" >&2

function _in_path() {
	command -v "$1" >/dev/null 2>&1
}

_sdkman_path="$HOME/.sdkman/bin/sdkman-init.sh"
[[ -f $_sdkman_path ]] && . "$_sdkman_path"

function _install_sdkman_kscript() {
	if declare -f sdk >/dev/null; then
		echo -en "[->     ] SDKMAN is installed...      \r" >&2
	else
		echo -en "[>      ] Checking dependencies...    \r" >&2

		if ! _in_path curl; then
			echo "'curl' is not installed...            "
			packager install curl || exit 1
		fi

		if ! _in_path zip; then
			echo "'zip' is not installed..."
			packager install zip || exit 1
		fi

		if ! _in_path unzip; then
			echo "'unzip' is not installed..."
			packager install unzip || exit 1
		fi

		echo "[->     ] Installing SDKMAN..." >&2
		curl -L "https://get.sdkman.io" | bash >/dev/null 2>/dev/null
		source "$_sdkman_path"
	fi

	if ! _in_path java; then
		echo -en "[-->   ] Installing java...          \r" >&2
		sdk install java >/dev/null 2>/dev/null
	fi

	if ! _in_path kotlin; then
		echo -en "[--->  ] Installing kotlin...          \r" >&2
		sdk install kotlin >/dev/null 2>/dev/null
	fi

	if ! _in_path gradle; then
		echo -en "[----> ] Installing gradle...          \r" >&2
		sdk install gradle >/dev/null 2>/dev/null
	fi

	if ! _in_path kscript; then
		echo -en "[----->] Installing kscript...          \r" >&2
		sdk install kscript >/dev/null 2>/dev/null
	fi

	source "$_sdkman_path"
}

if ! _in_path kscript; then
	if [[ -t 0 ]]; then # stdin is a terminal, the user can input data
		announce-menu --title "This script uses 'kscript', which is missing from your system." \
			"sdkman:Install kscript with SDKMAN, a non-root packager manager" \
			"packager:Use BrainDot's Packager tool to install kscript with your favorite package manager" \
			"quit:Stop and exit without doing anything"
		case "$(announce-menu-get)" in
		sdkman)
			_install_sdkman_kscript
			;;
		packager)
			packager install kscript
			;;
		quit)
			exit 0
			;;
		esac
	else
		_install_sdkman_kscript
	fi
fi

echo -en "Working...                                                          \r" >&2
exec kscript "$@"
