#!/bin/bash

git log \
    --color \
    --graph \
    --pretty=tformat:'%Cred%h%Creset ->%C(yellow)③%d%Creset %s %n%Cgreen%cr③     %Cresetby %C(bold blue)%an %CredSIG:%G?%GS%Creset%n' \
    --abbrev-commit \
    $* \
	| sed -f ${CLOVIS_CONFIG:-$HOME/config}/sed-git-log.sed \
	| column -t -s '③' \
	| less -rFX
