#!/bin/bash

announce "Starting Git Review..."

announce -nn "Source:"
git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ \1/' -e 's/^[[:space:]]*//'

announce -nn "Target:"
read -i master -e TARGET

COMMITS=$(git log --reverse --pretty=format:'%h' $TARGET..)

announce "There are" $(echo $COMMITS | wc -w) "commits. How do you want to review them?"
echo " 0. One-by-one"
echo " 1. As one"
announce -nn "Your choice:"
read REVIEW_MODE

function as-one {
    git diff $TARGET..

    announce -nn "Accept? (y/N)"
    read ACCEPT

    case $ACCEPT in
    y|yes)
        echo "Merge accepted.";;
    *)
        echo "Aborting."
        exit 0;;
    esac
}

function one-by-one {
    for COMMIT in $COMMITS
    do
        git show --show-signature $COMMIT

        announce -nn "Accept? (y/N)"
        read ACCEPT

        case $ACCEPT in
        y|yes)
            echo "Commit $COMMIT accepted.";;
        *)
            echo "Aborting."
            exit 0;;
        esac
    done
    announce "You accepted all commits."
}

case $REVIEW_MODE in
0)
    one-by-one;;
1)
    as-one;;
*)
    echo "Wrong input."
    exit 1;;
esac

announce "Choose your merge method:"
echo " 0. Merge     Recommended for beginners"
echo " 1. Rebase    Cleaner, but harder"
echo " 2. Squash    Not recommended"
announce -nn "Your choice:"
read MERGE_METHOD

function merge {
    OPTIONS="--stat --no-squash"

    if git merge-base --is-ancestor $TARGET HEAD
    then
        announce -nn "This branch can be fast-forwarded. Do you want to? (y/N)"
        read ALLOW_FF

        case $ALLOW_FF in
        y|yes)
            echo "Allowing fast-forward..."
            OPTIONS+=" --ff-only";;
        *)
            echo "Forbidding fast-forward..."
            OPTIONS+=" --no-ff";;
        esac
    fi

    announce " $ git merge $OPTIONS $TARGET"
    git merge $OPTIONS $TARGET
}

function rebase {
    announce " $ git rebase $TARGET"
    git rebase $TARGET
}

function squash {
    announce " $ git merge --stat --squash $TARGET"
    git merge --stat --squash $TARGET
}

case $MERGE_METHOD in
0|m|merge)
    merge;;
1|r|rebase)
    rebase;;
2|s|squash)
    squash;;
*)
    echo "Wrong input.";;
esac
