#!/bin/bash

git data --check-repo 2>/dev/null || exit 0

fetch_head=$(git data --git-dir)/FETCH_HEAD
[[ ! -f "$fetch_head" ]] && should_fetch=true

if [[ $should_fetch != true ]]; then
	last_fetch=$(stat -c %Y "$fetch_head")
	now=$(date +%s)
	diff=$((now - last_fetch))

	[[ $diff -gt 600 ]] && should_fetch=true
fi

if [[ $should_fetch == true ]]; then
	announce "Automatically fetching the repository $(git data --root)..."
	git fetch --all --prune || exit 1
	echo
fi

if [[ $should_fetch == true || $1 == "--changelog" ]]; then
	[[ $(git data --tracked) == "" ]] && exit 0
	COMMITS=$(git log .."$(git data --tracked)")
	if [[ "$COMMITS" != "" ]]; then
		git changelog .."$(git data --tracked)"
	fi
fi
