#!/bin/bash

announce "Choose your style:"
echo 0. Classic
echo 1. Angular
announce -nn "Your choice:"
read -r STYLE

function classic {
    announce -nn "Choose your commit message:"
    read -r MSG

    git commit -m "$MSG"
}

function angular {
    announce "Choose the type:"
    echo "0. build — build system, dependencies"
    echo "1. ci — CI/CD"
    echo "2. docs — documentation changes (internal or public)"
    echo "3. feat — new features, backward-compatible"
    echo "4. fix — fix problems, backward-compatible"
    echo "5. perf — better performances, backward-compatible"
    echo "6. refactor — changes to the product, backward-compatible"
    echo "7. style — grammar, coding style, linting..."
    echo "8. test — new tests, refactoring tests..."
    echo "9. breaking — backward-incompatible changes"
    announce -nn "Your choice:"
    read -r CHOICE_TYPE

    case $CHOICE_TYPE in
    0)
        TYPE=build;;
    1)
        TYPE=ci;;
    2)
        TYPE=docs;;
    3)
        TYPE=feat;;
    4)
        TYPE=fix;;
    5)
        TYPE=perf;;
    6)
        TYPE=refactor;;
    7)
        TYPE=style;;
    8)
        TYPE=test;;
    9)
        TYPE=breaking;;
    *)
        echo "Wrong input."
        angular;;
    esac

    announce -nn "Scope of the commit (can be empty for top-level):"
    read -r SCOPE

    announce -nn "Commit message:"
    read -r MESSAGE

    git commit -m "$TYPE($SCOPE): $MESSAGE"
}

case $STYLE in
0|classic)
    classic
    ;;
1|angular)
    angular
    ;;
*)
    echo "Wrong input."
    exit 1;;
esac
