#!/bin/bash

case $1 in
--check-repo)
	[[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" == 'true' ]] || \
	[[ "$(git rev-parse --is-bare-repository 2>/dev/null)" == 'true' ]]
	;;
--tracked)
	# From https://stackoverflow.com/a/9753364/5666171
	git for-each-ref --format='%(upstream:short)' "$(git symbolic-ref -q HEAD)";;
--current)
	git rev-parse --abbrev-ref HEAD;;
esac
