#!/bin/bash

git log \
    --color \
    --graph \
    --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an> %CredSIG:%G?%GS%Creset' \
    --abbrev-commit \
    $* | sed -f ~/config/sed-git-log.sed | less -rFX
