#!/bin/bash

case $1 in
enabled)
    hash pacman 2>/dev/null || (echo "'pacman' is not installed."; exit 1)
    ;;
name)
    echo -n "pacman"
    ;;
install)
    shift
    announce "pacman -S --needed $*"
    sudo pacman -S --needed $*
    ;;
upgrade)
    shift
    announce "pacman -Syyuu $*"
    sudo pacman -Syyuu $*
    ;;
remove)
    shift
    announce "pacman -R $*"
    sudo pacman -R --confirm $*
    ;;
purge)
    shift
    announce "pacman -Rncs $*"
    sudo pacman -Rncs --confirm $*
    ;;
search)
    shift
    announce "Where do you want to search on?"
    echo " 0. All packages"
    echo " 1. Installed packages"
    echo " 2. Search for a file"
    announce -nn "Your choice:"
    read -r CHOICE
    case $CHOICE in
    0|a|all)
        announce "pacman -Ss $*"
        pacman -Ss $*
        ;;
    1|i|installed)
        announce "pacman -Qi $*"
        pacman -Qi $*
        ;;
    2|f|file)
        announce "pacman -F $*"
        pacman -F $*
        ;;
    esac
    ;;
*)
    announce "Invalid command '$1'."
    exit 2
    ;;
esac
