#!/bin/bash

case $1 in
enabled)
    hash pacman 2>/dev/null || (echo "'pacman' is not installed."; exit 1)
    ;;
name)
    echo -n "pacman"
    ;;
install)
    shift
    announce "pacman -S --needed $*"
    sudo pacman -S --needed $*
    ;;
upgrade)
    shift
    announce "pacman -Syyuu $*"
    sudo pacman -Syyuu $*
    ;;
remove)
    shift
    announce "pacman -R $*"
    sudo pacman -R --confirm $*
    ;;
purge)
    shift
    announce "pacman -Rncs $*"
    sudo pacman -Rncs --confirm $*
    ;;
*)
    announce "Invalid command '$1'."
    exit 2
    ;;
esac
