#!/bin/bash

. cl-depend announce "tasker"

if [[ $1 == "--dir" ]]; then
	options+=" --workdir $2 "
	shift
	shift
fi

echo " → Starting '$*' with options '$options'"
command=". ~/config/selector.sh"
command+=" && announce Welcome to Tasker"
command+=" && echo Running: $* && echo"
command+=" && $*"
command+=" && exit"
command+=" || echo -e 'Something went wrong, press enter to close.' && read"
# shellcheck disable=SC2086
konsole $options --new-tab -e "$(command -v bash)" -c "$command" 2>/dev/null &
